apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: mysql-secret
        ports:
          - containerPort: 5000
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /tmp/liveness.sh
          initialDelaySeconds: 60
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin-port
    port: 5000
    targetPort: 5000
