apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: $INFLUX_URL
    user: $INFLUX_USER
    database: telegraf
    isDefault: true
    jsonData:
      httpMode: GET
    secureJsonData:
      password: $INFLUX_PASSWORD
    version: 1
    #editable: false
